### ISSUE TITLE
The curious case of the broken link

### ISSUE THREAD

**Issue by nchlswhttkr** [mossbanay/mossbanay.github.io#1]
Hey Moss,

I was checking your blog post on websockets in Elm, and the link to [the example repo](https://github.com/leaen/elm_websockets_example) is giving a 404 at the moment.

The repo's URL is `https://github.com/leaen/elm_websockets_example`, while the URL in the [published post](https://github.com/leaen/leaen.github.io/blob/fbc8a4625f5f36e28a1cbb567a997706e9e86d32/websockets-in-elm/index.html#L151) is `https://github.com/leaen/elm%5Fwebsockets%5Fexample`.

Somewhere along the line the underscores are being percent-encoded. Maybe Ghost CMS is doing something?

GitHub doesn't seem to do automatic conversion of percent-encoded characters in this situation, so the repo names are _technically different_.

It's worth noting that some browsers (Firefox/Chrome) obscure this percent-encoding in the address bar, so I'm shown a 404 even though the URL looks correct.

Cheers, Nicholas

**Comment by mossbanay** [comment]
Hey good spot! It looks like the link has garbled when I exported from my org file to markdown with `ox-hugo`. I've updated it to just use hyphens instead, should be working now.

**Comment by kaushalmodi** [comment]
Maybe this is not needed any more now that Hugo defaults to Goldmark.. I might remove the replacement of _ with %5F (ref: https://github.com/kaushalmodi/ox-hugo/issues/308).

**Comment by mossbanay** [comment]
If it helps I'm using Hugo 0.67.1 and ox-hugo commit 1c1e3e. The exported markdown and what is served in my browser (Firefox 74.0) has %5F in the link. Although it does look like I can click the link.
